# Generated by Django 4.2.7 on 2025-05-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrdDelivery',
            fields=[
                ('delcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('delmode', models.CharField(max_length=50)),
                ('deldt', models.DateField()),
                ('delstatus', models.CharField(max_length=50)),
                ('delcomnts', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyloc')),
            ],
            options={
                'verbose_name': 'Client Order Delivery',
                'verbose_name_plural': 'Client Order Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dddt', models.DateField()),
                ('paydt', models.DateField()),
                ('gamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('othrchrg1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('othrchrg2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('othrchrg3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('othrchrg4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('netamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recvdt', models.DateField()),
                ('advpay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rempay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advdt', models.DateField()),
                ('rempaydt', models.DateField()),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='TenderMast',
            fields=[
                ('tendid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tcalldt', models.DateField()),
                ('supname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyloc')),
                ('supid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
            options={
                'verbose_name': 'Tender Master',
                'verbose_name_plural': 'Tender Masters',
            },
        ),
        migrations.CreateModel(
            name='TenderIni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetp', models.CharField(max_length=20)),
                ('dmaker', models.CharField(max_length=100)),
                ('forunits', models.CharField(max_length=20)),
                ('measin', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyloc')),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Tender Initialization',
                'verbose_name_plural': 'Tender Initializations',
            },
        ),
        migrations.CreateModel(
            name='TenderDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forunits', models.CharField(max_length=20)),
                ('measin', models.CharField(max_length=10)),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('tendid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.tendermast')),
            ],
            options={
                'verbose_name': 'Tender Detail',
                'verbose_name_plural': 'Tender Details',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtyr', models.IntegerField()),
                ('rem', models.CharField(blank=True, max_length=255, null=True)),
                ('retdt', models.DateField()),
                ('invno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.invoice')),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'verbose_name_plural': 'Sales Returns',
            },
        ),
        migrations.CreateModel(
            name='PurchaseMast',
            fields=[
                ('purid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sorddt', models.DateField()),
                ('srecvdt', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyloc')),
                ('supid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Master',
                'verbose_name_plural': 'Purchase Masters',
            },
        ),
        migrations.CreateModel(
            name='PayDet',
            fields=[
                ('payno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('paytype', models.CharField(max_length=50)),
                ('ddchqno', models.CharField(blank=True, max_length=50, null=True)),
                ('ddchqdt', models.DateField(blank=True, null=True)),
                ('on', models.CharField(blank=True, max_length=100, null=True)),
                ('pstatus', models.CharField(max_length=50)),
                ('payfor', models.CharField(max_length=50)),
                ('invno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.invoice')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='OrdMast',
            fields=[
                ('ordno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ordt', models.DateField(auto_now_add=True)),
                ('reqdt', models.DateField()),
                ('totamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cltid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
            options={
                'verbose_name': 'Order Master',
                'verbose_name_plural': 'Order Masters',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='ordno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordmast'),
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('trackingid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cloc', models.CharField(max_length=100)),
                ('transno', models.CharField(max_length=50)),
                ('tmreach', models.IntegerField()),
                ('dtreach', models.DateField()),
                ('tremks', models.CharField(blank=True, max_length=255, null=True)),
                ('delcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.clientorddelivery')),
            ],
            options={
                'verbose_name': 'Delivery Tracking',
                'verbose_name_plural': 'Delivery Trackings',
            },
        ),
        migrations.AddField(
            model_name='clientorddelivery',
            name='invno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.invoice'),
        ),
        migrations.CreateModel(
            name='ClientOrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qtygv', models.IntegerField()),
                ('ordno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordmast')),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Client Order',
                'verbose_name_plural': 'Client Orders',
            },
        ),
        migrations.CreateModel(
            name='BranchPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqty', models.IntegerField()),
                ('pamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.purchasemast')),
            ],
            options={
                'verbose_name': 'Branch Purchase',
                'verbose_name_plural': 'Branch Purchases',
            },
        ),
    ]
