# Generated by Django 4.2.7 on 2025-05-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('prate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mfd', models.DateField()),
                ('pdesc', models.TextField()),
                ('madeof', models.CharField(max_length=100)),
                ('wt', models.CharField(max_length=20)),
                ('wtunit', models.CharField(max_length=10)),
                ('minstk', models.IntegerField()),
                ('reorderstk', models.IntegerField()),
                ('pforunit', models.IntegerField()),
                ('img', models.ImageField(default='products/default.jpg', upload_to='products/')),
                ('pcat', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProdStockMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stkdt', models.DateField(auto_now_add=True)),
                ('stktype', models.CharField(max_length=50)),
                ('stkqty', models.IntegerField()),
                ('stkunit', models.CharField(max_length=10)),
                ('currstk', models.IntegerField()),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Stock Master',
                'verbose_name_plural': 'Product Stock Masters',
            },
        ),
        migrations.CreateModel(
            name='BranchStk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('dt', models.DateField(auto_now_add=True)),
                ('unit', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyloc')),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Branch Stock',
                'verbose_name_plural': 'Branch Stocks',
            },
        ),
    ]
